Repository mattbrictson/bundle_update_interactive, pull requests merged in 2024-08, with the labels that each got.

#22 Drop Faraday dependency and use plain Net::HTTP instead
  bundle_update_interactive.gemspec
  lib/bundle_update_interactive.rb
  lib/bundle_update_interactive/changelog_locator.rb
  lib/bundle_update_interactive/http.rb
Labels: 🏠 Housekeeping

#29 Use correct Bundler version when updating gems
  lib/bundle_update_interactive/bundler_commands.rb
  test/bundle_update_interactive/bundler_commands_test.rb
Labels: 🐛 Bug Fix

#31 Improve `--help` output with description, options, and examples
  lib/bundle_update_interactive/cli/options.rb
  test/bundle_update_interactive/cli/options_test.rb
  test/bundle_update_interactive/cli_test.rb
Labels: 📚 Docs

#18 Change all/reverse key bindings to unmodified a/r
  images/update-interactive.png
  lib/bundle_update_interactive/cli/multi_select.rb
  test/bundle_update_interactive/cli/multi_select_test.rb
  test/support/capture_io_helpers.rb
Labels: ✨ Feature

#32 Open changelog url when `o` key is pressed
  bundle_update_interactive.gemspec
  images/update-interactive.png
  lib/bundle_update_interactive/cli/multi_select.rb
  lib/bundle_update_interactive/outdated_gem.rb
  test/bundle_update_interactive/cli/multi_select_test.rb
Labels: ✨ Feature

#35 Pin activesupport version used for testing to fix factory_bot issue
  Gemfile
Labels: 🏠 Housekeeping

#34 Fix crash when displaying prerelease → final version change
  lib/bundle_update_interactive/semver_change.rb
  test/bundle_update_interactive/semver_change_test.rb
Labels: 🐛 Bug Fix

#36 Refactor report and table API in anticipation of new features
  lib/bundle_update_interactive.rb
  lib/bundle_update_interactive/cli.rb
  lib/bundle_update_interactive/cli/multi_select.rb
  lib/bundle_update_interactive/cli/row.rb
  lib/bundle_update_interactive/cli/table.rb
  lib/bundle_update_interactive/report.rb
  lib/bundle_update_interactive/reporter.rb
  test/bundle_update_interactive/cli_test.rb
  test/bundle_update_interactive/reporter_test.rb
  test/snapshots/bundleupdateinteractive_reportertest/test_generates_a_report_of_updatable_gems_for_development_and_test_groups__1.snap.yaml
  test/snapshots/bundleupdateinteractive_reportertest/test_generates_a_report_of_updatable_gems_that_can_be_rendered_as_a_table__1.snap.yaml
Labels: 🏠 Housekeeping

#40 Install `zeitwerk` to simplify auto-loading
  bundle_update_interactive.gemspec
  lib/bundle_update_interactive.rb
  lib/bundle_update_interactive/cli.rb
Labels: 🏠 Housekeeping

#41 Add a true integration test that actually executes Bundler
  test/bundle_update_interactive/cli_test.rb
  test/factories/outdated_gems.rb
  test/fixtures/integration/Gemfile
  test/fixtures/integration/Gemfile.lock
  test/integration/cli_integration_test.rb
  test/support/mocha.rb
  test/test_helper.rb
Labels: 🏠 Housekeeping

#39 chore: add proper pluralization
  lib/bundle_update_interactive/cli/multi_select.rb
  lib/bundle_update_interactive/string_helper.rb
  test/bundle_update_interactive/cli_test.rb
Labels: 🐛 Bug Fix

#42 Add `--latest` option that modifies Gemfile to allow latest updates
  README.md
  lib/bundle_update_interactive/bundler_commands.rb
  lib/bundle_update_interactive/cli.rb
  lib/bundle_update_interactive/cli/options.rb
  lib/bundle_update_interactive/latest/gem_requirement.rb
  lib/bundle_update_interactive/latest/gemfile_editor.rb
  lib/bundle_update_interactive/latest/updater.rb
  lib/bundle_update_interactive/report.rb
  lib/bundle_update_interactive/updater.rb
  test/bundle_update_interactive/bundler_commands_test.rb
  test/bundle_update_interactive/cli/options_test.rb
  test/bundle_update_interactive/cli_test.rb
  test/bundle_update_interactive/latest/gem_requirement_test.rb
  test/bundle_update_interactive/latest/gemfile_editor_test.rb
  test/bundle_update_interactive/latest/updater_test.rb
  test/bundle_update_interactive/updater_test.rb
  test/integration/cli_integration_test.rb
  test/snapshots/bundleupdateinteractive_updatertest/test_generates_a_report_of_updatable_gems_for_development_and_test_groups__1.snap.yaml
  test/snapshots/bundleupdateinteractive_updatertest/test_generates_a_report_of_updatable_gems_that_can_be_rendered_as_a_table__1.snap.yaml
  test/snapshots/bundleupdateinteractive_updatertest/test_generates_a_report_of_withheld_gems_based_on_pins_that_excludes_updatable_gems__1.snap.yaml
Labels: ✨ Feature
