Repository mattbrictson/bundle_update_interactive, pull requests merged in 2024-07, with the labels that each got.

#1 Expand list of gems to install to work around conservative update
  lib/bundle_update_interactive/cli.rb
Labels: 🐛 Bug Fix, automerge

#2 Support older versions of Ruby that lack `Array#intersect?`
  lib/bundle_update_interactive/cli/thor_ext.rb
  lib/bundle_update_interactive/report.rb
Labels: 🐛 Bug Fix, automerge

#3 Add test coverage for `SemverChange`
  .rubocop.yml
  test/bundle_update_interactive/semver_test.rb
Labels: 🏠 Housekeeping, automerge

#4 Add Vim- and Emacs-like up/down keybindings
  lib/bundle_update_interactive/cli/multi_select.rb
Labels: ✨ Feature

#5 Refactor `OutdatedGem`; install FactoryBot for improved test coverage
  .rubocop.yml
  Gemfile
  lib/bundle_update_interactive/cli/table.rb
  lib/bundle_update_interactive/outdated_gem.rb
  lib/bundle_update_interactive/report.rb
  test/bundle_update_interactive/cli/row_test.rb
  test/factories/outdated_gems.rb
  test/support/factory_bot.rb
  test/test_helper.rb
Labels: 🏠 Housekeeping

#6 Properly handle non-GitHub git sources when inferring changelog URI
  lib/bundle_update_interactive/outdated_gem.rb
  test/bundle_update_interactive/outdated_gem_test.rb
Labels: 🐛 Bug Fix

#8 Fix a bug preventing CHANGELOG.md files from being discovered
  lib/bundle_update_interactive/changelog_locator.rb
  test/bundle_update_interactive/changelog_locator_test.rb
  test/cassettes/BundleUpdateInteractive/ChangelogLocatorTest/test_discovers_changelog_file_on_github.yml
  test/snapshots/bundleupdateinteractivetest/test_it_renders_updateable_gems__1.snap.yaml
Labels: 🐛 Bug Fix, automerge

#9 Document Features, Prior Art, etc. in README
  README.md
  images/conservative.png
  images/security.png
  images/semver.png
  images/update-interactive.png
  images/version-highlight.png
Labels: 📚 Docs

#10 Add support for Bitbucket Cloud diff URLs
  README.md
  lib/bundle_update_interactive/outdated_gem.rb
  test/bundle_update_interactive/outdated_gem_test.rb
Labels: ✨ Feature

#11 Add support for GitLab diff URLs
  README.md
  lib/bundle_update_interactive/outdated_gem.rb
  test/bundle_update_interactive/outdated_gem_test.rb
Labels: ✨ Feature

#12 Add changelog test coverage and refactor implementation for clarity
  lib/bundle_update_interactive/changelog_locator.rb
  test/bundle_update_interactive/changelog_locator_test.rb
  test/cassettes/BundleUpdateInteractive/ChangelogLocatorTest/test_discovers_changelog_file_on_github_after_following_redirect.yml
  test/cassettes/BundleUpdateInteractive/ChangelogLocatorTest/test_discovers_github_releases_url.yml
  test/cassettes/BundleUpdateInteractive/ChangelogLocatorTest/test_falls_back_to_top_level_rubygems_data_when_version_does_not_exist.yml
  test/cassettes/BundleUpdateInteractive/ChangelogLocatorTest/test_fetches_changelog_uri_from_rubygems.yml
  test/cassettes/BundleUpdateInteractive/ChangelogLocatorTest/test_returns_nil_when_changelog_cannot_be_discovered.yml
Labels: 🏠 Housekeeping

#17 Remove internal constants from global scope
  lib/bundle_update_interactive/changelog_locator.rb
Labels: 🏠 Housekeeping
